[workspace]
resolver = "3"
members = [
    "crates/ai-sdk-provider",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["saribmahmood55@gmail.com"]
repository = "https://github.com/saribmah/ai-sdk"

[workspace.dependencies]
